### ISSUE TITLE
Complete github community standards checklist

### ISSUE THREAD

**Issue by MetricMike** [MetricMike/asdf-awscli#23]
https://github.com/MetricMike/asdf-awscli/community

- [ ] Description
- [ ] Code of conduct (consider opening issue on https://github.com/asdf-vm/asdf-plugin-template/issues?q=code+of+conduct ?)
- [ ] Security policy (see: https://github.com/asdf-vm/asdf-plugin-template/issues/3)
- [ ] Pull request template (https://github.com/MetricMike/asdf-awscli/blob/main/.github/PULL_REQUEST/pull_request_template.md doesn't count?)
