### ISSUE TITLE
Improve local development/testing workflow

### ISSUE THREAD

**Issue by MetricMike** [MetricMike/asdf-awscli#24]
**Is your feature request related to a problem? Please describe.**

Kinda stuck in error-driven development - make a change, commit, wait for Github Actions, guess at fix for whatever build is failing. Developing this plugin could be much easier!

**Describe the solution you'd like**

(split these into other tickets)

- [ ] Examples/workflow for a more robust debugger like [BashDB](https://marketplace.visualstudio.com/items?itemName=rogalmic.bash-debug)
- [ ] Examples/workflow for making a change, and testing locally (point to git repo on disk instead of github? BATS?)
- [ ] Setup codespaces so a collaborator can just `.` on this page, apply fix, and publish a PR in ~10 minutes (arbitrary number) with nothing but a browser
- [ ] Document dependencies because it is so annoying to use something like long flags on uname and then have macos blow up in GithubActions (see: https://github.com/MetricMike/asdf-awscli/actions/runs/4794362683/jobs/8527665463#step:3:45 and https://github.com/asdf-vm/asdf/issues/1435)
- [ ] Implement caching/workflow reuse to speed up GithubActions? https://github.com/asdf-vm/actions/issues/235 https://github.com/asdf-vm/actions/issues/442
- [ ] Hook into ASDF BATS to ensure we're keeping up with upstream's requirements/best practices? https://github.com/asdf-vm/actions/issues/514 https://github.com/asdf-vm/asdf/issues/1512
  - [ ] also https://github.com/asdf-vm/asdf/issues/1318 https://github.com/bash-bastion and 
- [ ] Implement all scripts (the helper/dependencies ones are what I'm most excited about) https://github.com/asdf-vm/asdf-plugin-template/pull/61 https://asdf-vm.com/plugins/create.html#scripts-overview
- [ ] Implement benchmarking ala https://github.com/asdf-vm/asdf/issues/290 http://stratus3d.com/blog/2022/08/11/asdf-performance/
